project:
  type: book
  output-dir: docs

book:
  title: "GeneBridge: Inferring the Evolutionary Rooting of Orthologous Genes"
  author: "Dalmolin Systems Biology Group"
  chapters:
    - index.qmd
    - analysis/01_gene_rooting.qmd
    - analysis/02_plotting_roots.qmd
    - analysis/03_plotting_abundances.qmd
    - analysis/04_orthoguide.qmd
  reader-mode: true
  favicon: content/images/dalmolin_icon.svg
  site-url: https://dalmolingroup.imd.ufrn.br/genebridge-course/
  repo-url: https://github.com/dalmolingroup/genebridge-course
  page-footer:
      GeneBridge - Inferring the Evolutionary Rooting of Orthologous Genes is a course built by members of the
      <a href="https://dalmolingroup.imd.ufrn.br/">Dalmolin Systems Biology Group</a>.

knitr:
  opts_chunk:
    message: false
    warning: false
    results: false

format:
  pdf:
    keep-tex: true
    include-in-header: 
      text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error 
        }
    theme:
      light: flatly
      dark: darkly
  html:
    theme:
      light: flatly
      dark: darkly
    callout-appearance: simple
    code-link: true
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#b19cd9"
    highlight-style: github
